CREATE PROCEDURE fillDimDate
AS
BEGIN
  DECLARE @START_DATE DATE
  DECLARE @END_DATE DATE
  DECLARE @Y INT
  DECLARE @Q INT
  DECLARE @M INT
  DECLARE @D INT
  DECLARE @KEY BIGINT
  SET @START_DATE = '2000/01/01'
  SET @END_DATE = '2020/12/31'
  WHILE @START_DATE <= @END_DATE 
  BEGIN
    SET @Y = YEAR(@START_DATE)
    SET @M = MONTH(@START_DATE)
    SET @Q = CASE
      WHEN @M <= 3 THEN 1
      WHEN @M <= 6 THEN 2
      WHEN @M <= 9 THEN 3
      WHEN @M <= 12 THEN 4
    END
    SET @D = DAY(@START_DATE)
    SET @KEY = @D + (@M * 100) + (@Y * 10000)
    INSERT INTO dimDate VALUES (@KEY, @Y, @Q, @M, @D, @START_DATE)
    SET @START_DATE = DATEADD(DAY, 1, @START_DATE)
  END
END
